/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDiseaseRouteImport } from './routes/_authenticated/disease'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedFieldsIndexRouteImport } from './routes/_authenticated/fields.index'
import { Route as AuthenticatedFieldsNewRouteImport } from './routes/_authenticated/fields.new'
import { Route as AuthenticatedFieldsIdRouteImport } from './routes/_authenticated/fields.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/schemes/$id',
  path: '/schemes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiseaseRoute = AuthenticatedDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldsIndexRoute =
  AuthenticatedFieldsIndexRouteImport.update({
    id: '/fields/',
    path: '/fields/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldsNewRoute = AuthenticatedFieldsNewRouteImport.update({
  id: '/fields/new',
  path: '/fields/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldsIdRoute = AuthenticatedFieldsIdRouteImport.update({
  id: '/fields/$id',
  path: '/fields/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/home': typeof AuthenticatedHomeRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes/': typeof SchemesIndexRoute
  '/fields/$id': typeof AuthenticatedFieldsIdRoute
  '/fields/new': typeof AuthenticatedFieldsNewRoute
  '/fields/': typeof AuthenticatedFieldsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/home': typeof AuthenticatedHomeRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes': typeof SchemesIndexRoute
  '/fields/$id': typeof AuthenticatedFieldsIdRoute
  '/fields/new': typeof AuthenticatedFieldsNewRoute
  '/fields': typeof AuthenticatedFieldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRoute
  '/_authenticated/disease': typeof AuthenticatedDiseaseRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/schemes/': typeof SchemesIndexRoute
  '/_authenticated/fields/$id': typeof AuthenticatedFieldsIdRoute
  '/_authenticated/fields/new': typeof AuthenticatedFieldsNewRoute
  '/_authenticated/fields/': typeof AuthenticatedFieldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/advisor'
    | '/disease'
    | '/home'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/weather'
    | '/schemes/$id'
    | '/schemes/'
    | '/fields/$id'
    | '/fields/new'
    | '/fields/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/advisor'
    | '/disease'
    | '/home'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/weather'
    | '/schemes/$id'
    | '/schemes'
    | '/fields/$id'
    | '/fields/new'
    | '/fields'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/advisor'
    | '/_authenticated/disease'
    | '/_authenticated/home'
    | '/_authenticated/market'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/weather'
    | '/schemes/$id'
    | '/schemes/'
    | '/_authenticated/fields/$id'
    | '/_authenticated/fields/new'
    | '/_authenticated/fields/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  SchemesIdRoute: typeof SchemesIdRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/schemes/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disease': {
      id: '/_authenticated/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof AuthenticatedDiseaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fields/': {
      id: '/_authenticated/fields/'
      path: '/fields'
      fullPath: '/fields/'
      preLoaderRoute: typeof AuthenticatedFieldsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fields/new': {
      id: '/_authenticated/fields/new'
      path: '/fields/new'
      fullPath: '/fields/new'
      preLoaderRoute: typeof AuthenticatedFieldsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fields/$id': {
      id: '/_authenticated/fields/$id'
      path: '/fields/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof AuthenticatedFieldsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRoute
  AuthenticatedDiseaseRoute: typeof AuthenticatedDiseaseRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedFieldsIdRoute: typeof AuthenticatedFieldsIdRoute
  AuthenticatedFieldsNewRoute: typeof AuthenticatedFieldsNewRoute
  AuthenticatedFieldsIndexRoute: typeof AuthenticatedFieldsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRoute,
  AuthenticatedDiseaseRoute: AuthenticatedDiseaseRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedFieldsIdRoute: AuthenticatedFieldsIdRoute,
  AuthenticatedFieldsNewRoute: AuthenticatedFieldsNewRoute,
  AuthenticatedFieldsIndexRoute: AuthenticatedFieldsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  SchemesIdRoute: SchemesIdRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
